In [1]:
import torch

In [74]:
a = torch.rand([1,8,2])
a

tensor([[[0.6911, 0.9285],
         [0.9375, 0.5309],
         [0.8463, 0.2166],
         [0.9129, 0.3035],
         [0.1324, 0.1006],
         [0.7755, 0.1051],
         [0.1160, 0.7424],
         [0.0070, 0.6471]]])

In [75]:
b = a.squeeze(0)
b.shape

torch.Size([8, 2])

In [76]:
b

tensor([[0.6911, 0.9285],
        [0.9375, 0.5309],
        [0.8463, 0.2166],
        [0.9129, 0.3035],
        [0.1324, 0.1006],
        [0.7755, 0.1051],
        [0.1160, 0.7424],
        [0.0070, 0.6471]])

In [77]:
c = torch.argmax(b, dim=1)
c

tensor([1, 0, 0, 0, 0, 0, 1, 1])

In [6]:
from torchmetrics import Accuracy, Recall, Precision, F1Score

In [65]:
a = torch.tensor([
    [1,0],
    [0,1],
    [1,0],
    [1,0],
    [0,1],
    [0,1],
    [0,1],
    [0,1]
])

b = torch.tensor([
    [0,1],
    [0,1],
    [0,1],
    [1,0],
    [1,0],
    [0,1],
    [1,0],
    [1,0]
])

c = torch.rand([8,2])

print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

tensor([[1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]) torch.Size([8, 2])
tensor([[0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0]]) torch.Size([8, 2])
tensor([[0.4788, 0.7815],
        [0.7322, 0.7735],
        [0.7185, 0.5356],
        [0.6098, 0.1330],
        [0.6598, 0.4089],
        [0.1706, 0.2688],
        [0.1550, 0.6084],
        [0.1711, 0.5311]]) torch.Size([8, 2])


In [66]:
a = a.argmax(dim=1)
b = b.argmax(dim=1)

In [67]:
a

tensor([0, 1, 0, 0, 1, 1, 1, 1])

In [68]:
b

tensor([1, 1, 1, 0, 0, 1, 0, 0])

In [69]:
acc = Accuracy("binary", num_classes=2)
acc(a,b)

tensor(0.3750)

In [71]:
rec = Recall("binary", num_classes=2)
rec(a,b)

tensor(0.5000)

In [72]:
c

tensor([[0.4788, 0.7815],
        [0.7322, 0.7735],
        [0.7185, 0.5356],
        [0.6098, 0.1330],
        [0.6598, 0.4089],
        [0.1706, 0.2688],
        [0.1550, 0.6084],
        [0.1711, 0.5311]])

In [73]:
c = c.argmax(dim=1)
print(c, c.shape)

tensor([1, 1, 0, 0, 0, 1, 1, 1]) torch.Size([8])
