In [1]:
import torch

In [3]:
a = torch.rand([1,64,2])
a

tensor([[[0.8402, 0.5980],
         [0.0217, 0.7865],
         [0.2058, 0.8410],
         [0.9401, 0.7979],
         [0.5374, 0.2636],
         [0.7715, 0.6219],
         [0.4911, 0.3343],
         [0.2215, 0.5045],
         [0.8740, 0.0232],
         [0.6569, 0.0648],
         [0.5262, 0.2686],
         [0.5643, 0.3097],
         [0.6787, 0.8740],
         [0.0667, 0.6212],
         [0.4687, 0.2307],
         [0.1225, 0.4391],
         [0.8562, 0.0997],
         [0.0071, 0.5206],
         [0.6754, 0.7769],
         [0.0463, 0.1940],
         [0.2966, 0.2101],
         [0.4895, 0.1370],
         [0.9771, 0.1045],
         [0.5657, 0.0331],
         [0.8216, 0.8241],
         [0.8987, 0.3105],
         [0.6638, 0.9852],
         [0.1869, 0.0019],
         [0.1434, 0.6041],
         [0.8836, 0.1897],
         [0.2798, 0.1045],
         [0.7715, 0.4802],
         [0.9680, 0.0380],
         [0.9215, 0.2293],
         [0.5599, 0.6537],
         [0.5373, 0.3195],
         [0.2859, 0.9135],
 

In [5]:
b = a.squeeze(0)
b.shape

torch.Size([64, 2])

In [6]:
from torchmetrics import Accuracy, Recall, Precision, F1Score

In [65]:
a = torch.tensor([
    [1,0],
    [0,1],
    [1,0],
    [1,0],
    [0,1],
    [0,1],
    [0,1],
    [0,1]
])

b = torch.tensor([
    [0,1],
    [0,1],
    [0,1],
    [1,0],
    [1,0],
    [0,1],
    [1,0],
    [1,0]
])

c = torch.rand([8,2])

print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

tensor([[1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]) torch.Size([8, 2])
tensor([[0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0]]) torch.Size([8, 2])
tensor([[0.4788, 0.7815],
        [0.7322, 0.7735],
        [0.7185, 0.5356],
        [0.6098, 0.1330],
        [0.6598, 0.4089],
        [0.1706, 0.2688],
        [0.1550, 0.6084],
        [0.1711, 0.5311]]) torch.Size([8, 2])


In [66]:
a = a.argmax(dim=1)
b = b.argmax(dim=1)

In [67]:
a

tensor([0, 1, 0, 0, 1, 1, 1, 1])

In [68]:
b

tensor([1, 1, 1, 0, 0, 1, 0, 0])

In [69]:
acc = Accuracy("binary", num_classes=2)
acc(a,b)

tensor(0.3750)

In [71]:
rec = Recall("binary", num_classes=2)
rec(a,b)

tensor(0.5000)

In [72]:
c

tensor([[0.4788, 0.7815],
        [0.7322, 0.7735],
        [0.7185, 0.5356],
        [0.6098, 0.1330],
        [0.6598, 0.4089],
        [0.1706, 0.2688],
        [0.1550, 0.6084],
        [0.1711, 0.5311]])

In [73]:
c = c.argmax(dim=1)
print(c, c.shape)

tensor([1, 1, 0, 0, 0, 1, 1, 1]) torch.Size([8])
