In [1]:
import torch

In [9]:
x = torch.tensor([1,2,3,4])
x.shape

torch.Size([4])

In [10]:
a = x.unsqueeze(1)
a

tensor([[1],
        [2],
        [3],
        [4]])

In [11]:
a.shape

torch.Size([4, 1])

In [12]:
b = x.unsqueeze(0)
b

tensor([[1, 2, 3, 4]])

In [13]:
b.shape

torch.Size([1, 4])

In [15]:
c = b.squeeze(0)
c

tensor([1, 2, 3, 4])